# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C3TPhIPIsD7ZQHZG_mIU6XtFlnQRP9tz
"""

def fibonacci(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b

# Используем генератор
for num in fibonacci(5):
    print(num)

"""Neste exemplo, o gerador Fibonacci calcula números sob demanda em vez de armazenar todos os valores na memória. Isto torna os geradores especialmente adequados para trabalhar com fluxos de dados ou sequências infinitas.

# **Outro modo de fazer o gerador**
"""

def factorial(n):
    if n == 0:
        return 1  # Базовый случай
    else:
        return n * factorial(n - 1)  # Рекурсивный вызов

print(factorial(5))  # Вывод: 120

"""É importante garantir que o caso base esteja definido corretamente, caso contrário a função poderá causar um estouro de pilha. A recursão é útil para problemas que podem ser divididos em subproblemas, como travessia de árvore ou resolução de problemas de sequência."""

# Outros exemplos

text = "Hello,\nWorld!"  # \n добавляет новую строку
print(text)

path = "C:\\Users\\Name\\Documents"  # \\ usado para adicionar uma barra invertida
print(path)

"""**Docstrings em Python** são usados ​​para documentar funções, classes e módulos. Eles ajudam os desenvolvedores a compreender o propósito e o uso do código. Uma Docstring é uma string entre aspas triplas colocada imediatamente após a definição da função. Pode conter uma descrição, parâmetros e valores de retorno. Exemplo de uso de docstring para uma função"""

def add(a, b):
    """
    Adds two numbers.

    Parameters:
    a (int or float): The first number.
    b (int or float): The second number.

    Returns:
    int or float: The sum of a and b.
    """
    return a + b

soma = add(4,7)
print(soma)

# Docstrings

print(add.__doc__)

"""**Um construtor em Python** é um método especial de uma classe que é chamado automaticamente quando um novo objeto dessa classe é criado. Em Python, um construtor é indicado pelo método __init__(). É utilizado para inicializar os atributos de um objeto e pode aceitar parâmetros para configurar o objeto quando ele é criado.

"""

class Car:
    def __init__(self, make, model, year):  # Конструктор класса Car
        self.make = make  # Инициализация атрибута make
        self.model = model  # Инициализация атрибута model
        self.year = year  # Инициализация атрибута year

my_car = Car('Toyota', 'Corolla', 2020)  # Создание объекта с использованием конструктора
print(my_car.make)
print(my_car.model)
print(my_car.year)

"""**O que é uma rede de decoradores e como usá-la**? O encadeamento de decoradores em Python é a aplicação sequencial de vários decoradores em uma única função. Cada decorador envolve uma função, adicionando ou alterando seu comportamento. Os decoradores são aplicados de cima para baixo, o que significa que o decorador superior é executado primeiro, depois o próximo e assim por diante. Exemplo de uma rede de decoradores"""

def decorator_one(func):
    def wrapper(*args, **kwargs):
        print("Decorator One")
        return func(*args, **kwargs)
    return wrapper

def decorator_two(func):
    def wrapper(*args, **kwargs):
        print("Decorator Two")
        return func(*args, **kwargs)
    return wrapper

@decorator_one
@decorator_two
def say_hello():
    print("Hello!")

say_hello()

"""Para ler todo o conteúdo de um arquivo de uma vez, Python usa o método read(). Este método lê todo o texto de um arquivo e o retorna como uma string. É importante lembrar que o arquivo deve ser aberto em modo leitura."""

with open('example.txt', 'r') as file:  # Открытие файла в режиме чтения
    content = file.read()  # Чтение всего содержимого файла
    print(content)  # Вывод содержимого файла

"""Usar a construção with garante que o arquivo será fechado normalmente quando você terminar de usá-lo, mesmo se ocorrer um erro. Isso torna o código mais seguro e confiável.

**NumPy** é uma biblioteca para Python que fornece suporte para arrays e matrizes multidimensionais, bem como funções para realizar operações matemáticas de alto nível. Para começar, você precisa instalar a biblioteca:
"""

!pip install numpy

"""A diferença entre !pip install numpy e pip install numpy está relacionada ao ambiente em que o comando é executado. O !pip install numpy é usado em ambientes de notebooks Jupyter, onde o ponto de exclamação (!) indica que o comando deve ser executado no sistema operacional, permitindo que você instale pacotes diretamente do notebook. Por outro lado, pip install numpy é o comando padrão para instalar pacotes Python em um terminal ou na linha de comando do sistema operacional.

O objeto NumPy principal é o array ndarray, que pode ser criado usando a função array():
"""

import numpy as np

arr = np.array([1, 2, 3, 4])

"""NumPy suporta uma ampla gama de operações de array, incluindo operações aritméticas que são executadas elemento por elemento:"""

arr2 = np.array([5, 6, 7, 8])
result = arr + arr2  # array([ 6,  8, 10, 12])
print(result)

"""NumPy также предоставляет функции для линейной алгебры, статистики и других численных вычислений:"""

matrix = np.array([[1, 2], [3, 4]])
det = np.linalg.det(matrix)  # Cálculo do determinante
mean = np.mean(arr)  # Valor médio
print(det)
print(mean)

"""O NumPy é otimizado para trabalhar com grandes quantidades de dados, tornando-o uma ferramenta indispensável para computação científica e de engenharia.

**Set** definido em Python é uma coleção não ordenada de elementos únicos. É usado para armazenar vários elementos sem duplicatas e suporta operações de conjunto como união, interseção e diferença. A criação de um conjunto pode ser feita usando chaves ou a função set():
"""

my_set = {1, 2, 3}
another_set = set([3, 4, 5])

"""Principais características do conjunto:
- Singularidade: todos os elementos de um conjunto são únicos. Adicionar uma duplicata não alterará o conjunto.
- Não ordenado: os elementos não possuem ordem fixa, portanto a indexação não está disponível.
- Mutabilidade: Elementos podem ser adicionados e removidos usando os métodos add() e remove().

Exemplos de operações em conjuntos:
"""

union_set = my_set | another_set  # {1, 2, 3, 4, 5}
intersection_set = my_set & another_set  # {3}
difference_set = my_set - another_set  # {1, 2}

print(union_set)
print(intersection_set)
print(difference_set)

difference_set = another_set - my_set
print(difference_set)

"""**set** é uma ferramenta eficaz para trabalhar com dados exclusivos e realizar operações em conjuntos

**SQLAlchemy é uma biblioteca de banco de dados Python** que fornece ferramentas para mapeamento relacional de objetos (ORM) e processamento de consultas SQL. Para começar, você precisa instalar a biblioteca:
"""

!pip install sqlalchemy

# A criação de uma conexão com o banco de dados é feita
# através do objeto create_engine

from sqlalchemy import create_engine

engine = create_engine('sqlite:///example.db')

"""Para definir a estrutura da tabela, um estilo declarativo é usado usando **declarative_base**:"""

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String
from sqlalchemy import or_, and_ # Import or_ and and_

Base = declarative_base()

class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    name = Column(String)

from sqlalchemy.orm import sessionmaker

Session = sessionmaker(bind=engine)
session = Session()

"""Adicionando e solicitando dados:"""

# Create the engine and session
engine = create_engine('sqlite:///example.db')

# Create all tables in the database (if they don't exist)
Base.metadata.create_all(engine)  # This line creates the 'users' table

Session = sessionmaker(bind=engine)
session = Session()

new_user = User(name='Alice')
session.add(new_user)
session.commit()

users = session.query(User).filter_by(name='Alice').all()

"""Para verificar se o registro foi gerado no banco de dados, você pode usar o código que já escreveu: users = session.query(User).filter_by(name='Alice').all(). Se o registro existiu e foi criado corretamente, a lista users deve conter um ou mais objetos User. Você pode imprimir o resultado ou verificar o comprimento da lista:

python
print(users)  # Para ver os objetos que foram retornados  
print(len(users))  # Para ver quantos registros foram encontrados  
Caso a lista esteja vazia (len(users) == 0), isso indica que não há registro com nome 'Alice' no banco de dados.
"""

print(users)  # Para ver os objetos que foram retornados
print(len(users))  # Para ver quantos registros foram encontrados

"""No SQLAlchemy, você pode realizar consultas usando diferentes filtros de várias maneiras. Aqui estão alguns exemplos comuns:

**Usando filter()**
O método filter() permite usar expressões mais complexas e combinações de filtros. Você pode usar operadores como ==, !=, >, <, like(), entre outros. Veja um exemplo:

from sqlalchemy import and_, or_  

# Consulta combinando filtros  
users = session.query(User).filter(  
    and_(User.name == 'Alice', User.age > 18)  
).all()  
**Usando filter_by()**
O método filter_by() é um método mais simples que se utiliza de parâmetros nomeados. Ele é ideal para filtros diretos e equivalentes. Exemplo:

# Consulta básica com filtro direto  
users = session.query(User).filter_by(name='Alice', active=True).all()

**Consultas com or_**
Para realizar consultas que atendam a múltiplas condições onde qualquer condição seja verdadeira, você pode usar or_:

from sqlalchemy import or_  

# Consulta usando 'or_'  
users = session.query(User).filter(  
    or_(User.name == 'Alice', User.name == 'Bob')  
).all()

**Filtrando com like()**
Se você quiser filtrar resultados baseados em padrões de string, pode usar o método like():

# Consulta usando like  
users = session.query(User).filter(User.name.like('%Ali%')).all()  # Nomes que contêm "Ali"  

**Exemplo Combinado**
Você pode combinar o uso de filter(), filter_by(), or_, e and_ em uma mesma consulta. Por exemplo:

from sqlalchemy import and_, or_  

# Consulta combinada  
users = session.query(User).filter(  
    or_(  
        User.name.like('%Ali%'),  
        and_(User.age < 20, User.active == True)  
    )  
).all()

Conclusão
Esses são apenas alguns exemplos de como você pode usar filtros diferentes no SQLAlchemy. Dependendo das suas necessidades, você pode combinar filtros conforme necessário para obter os resultados desejados.
"""

users = session.query(User).filter(
or_(User.name.like('%Ali%'))).all()

print(users)

"""O código que você forneceu está utilizando SQLAlchemy para fazer uma consulta em um banco de dados. Aqui está uma explicação detalhada do que ele faz e como você pode exibir o resultado mostrando o nome:

Explicação
session.query(User): Isso inicia uma consulta na tabela User.
.filter(and_(User.name == 'Alice')): Este filtro aplica uma condição onde o nome do usuário deve ser igual a 'Alice'.
.all(): Este método retorna todos os resultados que atendem à condição especificada.
Exibindo o Resultado
Após a consulta, você pode iterar sobre os resultados para exibir o nome. Aqui está um exemplo de como fazer isso:

python
from sqlalchemy import and_  

# Supondo que você já tenha uma sessão ativa  
users = session.query(User).filter(  
    and_(User.name == 'Alice')  
).all()  

# Exibindo os resultados  
for user in users:  
    print(f'Nome: {user.name}')  
Resultados
Se houver registros com o nome 'Alice', eles serão impressos no console. Caso contrário, nada será exibido.


"""

for user in users:
  print(f'Nome: {user.name}')